In [1]:
import numpy as np
from pprint import pprint

In [2]:
BIAS = 1 # N

THRESHOLD     = 0 # Objetivo da rede / threshold
MAX_ITERACOES = 10

# Dados
X = np.array([
    [BIAS, 1, 1],
    [BIAS, 1, 0],
    [BIAS, 0, 0],
    [BIAS, 0, 1],
])

# Resultados
y = np.array([
    [1, 0],
    [0, 0],
    [0, 1],
    [1, 1],
])

PESOS = [
    [0, 0], # W0 -> Bias
    [0, 0], # W1 -> X0
    [0, 0], # W2 -> X1
]

In [3]:
def ativacao_y(j, x):
    # A ativação realiza o calculo de um Y
    # Somatório de 0 até N
    # Vj = Xi * Wij
    v = 0
    
    for i in range(len(x)):
        v += x[i] * PESOS[i][j]
    
    return v

def transferencia(v):
    # f(v) { 1, para todo v >= 0
    #      { 0, para todo v < 0
    if v >= 0:
        return 1
    else:
        return 0;
    
def erro(esperado, calculado):
    # Calcula o erro para uma saída
    erro = esperado - calculado
    
    print("Erro: %d - Esperado: %d - Calculado: %d" %(erro, esperado, calculado))
    
    return erro
    
def atualiza_pesos(j, erros, entrada):
    # PesoAtualizado = PesoAntigo + Bias * Entrada * Erro
    for i in range(len(entrada)):
        peso = PESOS[i][j]
        erro = erros[j]
        print("Peso: %d - Entrada: %d - Erro: %d" %(peso, entrada[i], erro))
        peso = peso + BIAS * entrada[i] * erro
        PESOS[i][j] = peso
        
    pprint(PESOS)
    
def perceptron():
    # Reseta o erro global
    ERRO_GLOBAL = 0
    ERRO_RODADA = 0
        
    tam_dataset = len(X)
    
    # Quantidade de gerações
    for i in range(MAX_ITERACOES):
        geracao = i + 1
        print("Geracao: %d" % geracao)
    
        for j in range(tam_dataset):
            ERRO_RODADA = 0

            print("\nElemento: %d" %(j))

            # Recupera uma entrada
            x = X[j]
            pprint(x)

            # 1 - Função de ativação
            # Calcula a função de ativacao para Y0 e Y1
            a = [
                    ativacao_y(0, x),
                    ativacao_y(1, x)
                ]

            # 2 - Função de transferência
            # Calcula a função de transferência para Ativacao0 e Ativacao1
            t = [
                    transferencia(a[0]),
                    transferencia(a[1])
            ]

            # 3 - Calcula o erro
            # Calcula o erro da Transferencia0 e Transferencia1
            # Utiliza o resultado esperado - resultado calculado
            e = [
                    erro(y[j][0], t[0]), 
                    erro(y[j][1], t[1]),
                ]

            # 4 - Calcula os novos pesos
            atualiza_pesos(0, e, x)
            atualiza_pesos(1, e, x)

            # En^1 = |E0| + |E1\
            # ErroMedioN = Modulo(ErroSaida1) + Modulo(ErroSaida2)
            ERRO_RODADA += abs(e[0])
            ERRO_RODADA += abs(e[1])
            ERRO_GLOBAL += ERRO_RODADA
        
        # Erro global = (ErroMedio1 + ErroMedio2 + ...) / Qtde elementos de teste
        ERRO_GLOBAL /= tam_dataset

        print("\nErro Global: %d \n\n" % ERRO_GLOBAL)

        # Se atingiu o erro desejado, então deve para
        if ERRO_GLOBAL == THRESHOLD:
            break
    

In [4]:
perceptron()

Geracao: 1

Elemento: 0
array([1, 1, 1])
Erro: 0 - Esperado: 1 - Calculado: 1
Erro: -1 - Esperado: 0 - Calculado: 1
Peso: 0 - Entrada: 1 - Erro: 0
Peso: 0 - Entrada: 1 - Erro: 0
Peso: 0 - Entrada: 1 - Erro: 0
[[0, 0], [0, 0], [0, 0]]
Peso: 0 - Entrada: 1 - Erro: -1
Peso: 0 - Entrada: 1 - Erro: -1
Peso: 0 - Entrada: 1 - Erro: -1
[[0, -1], [0, -1], [0, -1]]

Elemento: 1
array([1, 1, 0])
Erro: -1 - Esperado: 0 - Calculado: 1
Erro: 0 - Esperado: 0 - Calculado: 0
Peso: 0 - Entrada: 1 - Erro: -1
Peso: 0 - Entrada: 1 - Erro: -1
Peso: 0 - Entrada: 0 - Erro: -1
[[-1, -1], [-1, -1], [0, -1]]
Peso: -1 - Entrada: 1 - Erro: 0
Peso: -1 - Entrada: 1 - Erro: 0
Peso: -1 - Entrada: 0 - Erro: 0
[[-1, -1], [-1, -1], [0, -1]]

Elemento: 2
array([1, 0, 0])
Erro: 0 - Esperado: 0 - Calculado: 0
Erro: 1 - Esperado: 1 - Calculado: 0
Peso: -1 - Entrada: 1 - Erro: 0
Peso: -1 - Entrada: 0 - Erro: 0
Peso: 0 - Entrada: 0 - Erro: 0
[[-1, -1], [-1, -1], [0, -1]]
Peso: -1 - Entrada: 1 - Erro: 1
Peso: -1 - Entrada: 0 - 